export const normalizeSeniority = (seniority) => {
    if (seniority === 'Semi Senior') return 'Semi-Senior';
    if (seniority === 'Mid Level') return 'Mid-Level';
    return seniority;
};

export const allRows = [
        ['Python', '', 'Senior'],
        ['', 'Django', 'Senior'],
        ['', 'Django REST Framework (DRF)', 'Senior'],
        ['', 'Wagtail', 'Semi Senior'],
        ['', 'Odoo', 'Semi Senior'],
        ['', 'Flask', 'Semi Senior'],
        ['', 'Pelican', 'Junior'],
        ['C#', '', 'Semi Senior'],
        ['', '.NET', 'Semi Senior'],
        ['', 'ASP.NET', 'Semi Senior'],
        ['', 'Unity', 'Junior'],
        ['Java', '', 'Semi Senior'],
        ['', 'Java Enterprise Edition (Java EE)', 'Junior'],
        ['', 'Android Studio', 'Junior'],
        ['JavaScript (JS)', '', 'Semi Senior'],
        ['Node.js', '', 'Semi Senior'],
        ['', 'Express.js', 'Semi Senior'],
        ['', 'TypeScript (TS)', 'Mid Level'],
        ['', 'React', 'Mid Level'],
        ['', 'Sails.js', 'Junior'],
        ['', 'Electron', 'Junior'],
        ['', 'Nightmare.js', 'Junior'],
        ['HTML', '', 'Mid Level'],
        ['CSS', '', 'Mid Level'],
        ['Ruby', '', 'Mid Level'],
        ['', 'Ruby on Rails (RoR)', 'Mid Level'],
        ['C++', '', 'Junior'],
        ['Haskell', '', 'Junior'],
        ['PHP', '', 'Junior'],
        ['Scilab', '', 'Junior'],
        ['Vue.js', '', 'Junior'],
        ['Machine Learning', '', '', 'Mid Level'],
        ['', '', 'Linear Regression', 'Mid Level'],
        ['', '', 'Naive Bayes', 'Mid Level'],
        ['', 'Neural Networks', '', 'Mid Level'],
        ['', '', 'Bidirectional Long Short-Term Memory', 'Mid Level'],
        ['Rule-based AI', '', '', 'Mid Level'],
        ['RASA', '', '', 'Mid Level'],
        ['PostgreSQL', '', 'Senior'],
        ['', 'DBeaver', 'Senior'],
        ['', 'pgAdmin', 'Semi Senior'],
        ['SQLite', '', 'Senior'],
        ['Microsoft SQL Server', '', 'Semi Senior'],
        ['', 'SQL Server Management Studio', 'Semi Senior'],
        ['Oracle SQL', '', 'Mid Level'],
        ['MySQL', '', 'Mid Level'],
        ['', 'phpMyAdmin', 'Mid Level'],
        ['MongoDB', '', 'Semi Senior'],
        ['', 'Mongoose', 'Semi Senior'],
        ['', 'MongoDB Compass', 'Semi Senior'],
        ['', 'Mongo Atlas Search', 'Junior'],
        ['Redis', '', 'Junior'],
        ['Git', 'Senior'],
        ['Github', 'Senior'],
        ['Github Actions', 'Senior'],
        ['Gitlab', 'Semi Senior'],
        ['SourceTree', 'Semi Senior'],
        ['Apache Subversion (SVN)', 'Semi Senior'],
        ['CircleCI', 'Mid Level'],
        ['Bitbucket', 'Mid Level'],
        ['Team Foundation Version Control', 'Mid Level'],
        ['Microsoft Azure', '', 'Senior'],
        ['', 'App Service', 'Senior'],
        ['', 'Azure Database for PostgreSQL', 'Senior'],
        ['', 'Function App', 'Semi Senior'],
        ['Amazon Web Services (AWS)', '', 'Senior'],
        ['', 'Elastic Beanstalk', 'Senior'],
        ['', 'Secrets Manager', 'Senior'],
        ['', 'Amazon Elastic Compute Cloud (EC2)', 'Senior'],
        ['', 'AWS Identity and Access Management (IAM)', 'Semi Senior'],
        ['', 'Amazon Simple Storage Service (S3)', 'Semi Senior'],
        ['', 'AWS Lambda', 'Semi Senior'],
        ['', 'Serverless', 'Semi Senior'],
        ['', 'Serverless Offline', 'Semi Senior'],
        ['', 'Amazon API Gateway (API Gateway)', 'Mid Level'],
        ['', 'Amazon CloudWatch (CloudWatch)', 'Mid Level'],
        ['', 'Amazon DynamoDB (DynamoDB)', 'Mid Level'],
        ['', 'AWS CodeDeploy', 'Junior'],
        ['', 'AWS CodePipeline', 'Junior'],
        ['', 'Amazon Simple Queue Service (SQS)', 'Junior'],
        ['GitHub Pages', '', 'Semi Senior'],
        ['Google Cloud', '', 'Mid Level'],
        ['', 'Compute Engine', 'Mid Level'],
        ['', 'App Engine', 'Mid Level'],
        ['Heroku', '', 'Junior'],
        ['DataDog', '', 'Junior'],
        ['Agile Development', '', '', 'Senior'],
        ['', 'Scrum', '', 'Senior'],
        ['', 'Custom Methodologies', '', 'Semi Senior'],
        ['', '', 'Software Development Life Cycle (SDLC) Iterative Incremental', 'Semi Senior'],
        ['', '', 'Software Development Life Cycle (SDLC) Incremental', 'Semi Senior'],
        ['', 'Lean Startup', '', 'Mid Level'],
        ['', '', 'Software Development Life Cycle (SDLC) Evolutionary', 'Mid Level'],
        ['Traditional Development', '', '', 'Semi Senior'],
        ['', '', 'Software Development Life Cycle (SDLC) Waterfall', 'Semi Senior'],
        ['Design Thinking', '', '', 'Semi Senior'],
        ['Team Leadership', '', '', 'Semi Senior'],
        ['Negotiation', '', '', 'Mid Level'],
        ['Windows', '', 'Senior'],
        ['Linux', '', 'Semi Senior'],
        ['', 'Ubuntu', 'Mid Level'],
        ['', 'Mint', 'Mid Level'],
        ['', 'Debian', 'Junior'],
        ['Mac', '', 'Semi Senior'],
        ['PyCharm', 'Senior'],
        ['Visual Studio', 'Senior'],
        ['Netbeans', 'Semi Senior'],
        ['Notepad++', 'Semi Senior'],
        ['Sublime Text', 'Semi Senior'],
        ['RubyMine', 'Semi Senior'],
        ['Fleet', 'Mid Level'],
        ['Visual Studio Code (VSCode)', 'Mid Level'],
        ['WebStorm', 'Mid Level'],
        ['Unity', 'Junior'],
        ['Android Studio', 'Junior'],
        ['Trello', 'Senior'],
        ['Jira', 'Senior'],
        ['Redmine', 'Mid Level'],
        ['Pivotal', 'Mid Level'],
        ['Representational State Transfer (REST)', 'Senior'],
        ['Postman', 'Senior'],
        ['Terraform', 'Semi Senior'],
        ['Docker + Docker-Compose', 'Semi Senior'],
        ['Celery', 'Mid Level'],
        ['VirtualBox', 'Mid Level'],
        ['Microsoft Internet Information Services (IIS)', 'Mid Level'],
        ['jQuery', 'Mid Level'],
        ['Markdown', 'Mid Level'],
        ['Smarty', 'Mid Level'],
        ['BNFC', 'Junior'],
        ['Desarrollo de Videojuegos', 'Junior'],
        ['Simple Object Access Protocol (SOAP)', 'Junior'],
        ['SoapUI', 'Junior'],
        ['Selenium', 'Junior'],
        ['Flower', 'Junior'],
        ['uWSGI', 'Junior'],
        ['Mocha', 'Junior'],
        ['Chai', 'Junior'],
        ['Fakingoose', 'Junior']
];

export const getAllSkillsData = () => {
    const skillSeniorityMap = {};

    allRows.forEach(row => {
        const seniorityIndex = row.length - 1;
        const seniority = normalizeSeniority(row[seniorityIndex]);
        const skillParts = row.slice(0, seniorityIndex).filter(part => part.trim() !== '');
        
        skillParts.forEach(skill => {
            const trimmedSkill = skill.trim();
            if (trimmedSkill !== '' && !skillSeniorityMap[trimmedSkill]) {
                skillSeniorityMap[trimmedSkill] = seniority;
            }
        });
    });

    return skillSeniorityMap;
};

export const seniorityDescriptions = {
    'Senior': 'Highly experienced and immediately productive with these technologies. I\'m well-versed in their latest best practices, methodologies, and have developed personal techniques I can share. Comfortable starting on any project, regardless of size or technical debt.',
    'Semi-Senior': 'Considerably experienced, comfortable, and familiar with its best practices and patterns. I may need a few days to refresh or master them if I haven\'t used them recently.',
    'Mid-Level': 'Used these technologies in personal projects or courses. I can apply general software engineering knowledge but need a few weeks of focused work to reach semi-senior level.',
    'Junior': 'Limited experience (1-2 months) with these techs, mainly for small tasks or projects. I can build simple software but need more practice to handle larger projects, potentially reaching mid-level in a few weeks with regular use.'
};

